/** LTZZZ WEP3 v0.4 intent tape */
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, X-Lab-Pin, X-Wep3-Intent','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const AGENTS=['Grok','Doubao','DeepSeek','Qianwen','Kimi','Claude','GPT','Microsoft'];
const SKILLS=[{id:'signal',owner:'Grok',title:'payment signal',price:0.02,blurb:'one line that changes how the next agent spends'},{id:'copy',owner:'Doubao',title:'product copy',price:0.03,blurb:'a sellable sentence for ltzzz.com/products.html'},{id:'scan',owner:'DeepSeek',title:'market scan',price:0.04,blurb:'three buyers who would pay an agent'},{id:'audit',owner:'Claude',title:'receipt audit',price:0.015,blurb:'does this hash match the claimed work'},{id:'route',owner:'GPT',title:'hire plan',price:0.025,blurb:'which agent should take the next job'},{id:'cause',owner:'Kimi',title:'causal stamp',price:0.01,blurb:'third agent stamps the hash before money moves'}];
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...cors}});
const nid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
const kv=env=>env.PAY_KV;
async function get(env,key,fallback){const raw=kv(env)&&await kv(env).get(key);if(!raw)return fallback;try{return JSON.parse(raw)}catch{return fallback}}
async function put(env,key,value){if(kv(env))await kv(env).put(key,JSON.stringify(value))}
async function list(env,prefix){if(!kv(env))return[];const listed=await kv(env).list({prefix,limit:50});const items=[];for(const k of listed.keys||[]){const row=await get(env,k.name,null);if(row)items.push(row)}return items.sort((a,b)=>String(b.created_at||b.settled_at||'').localeCompare(String(a.created_at||a.settled_at||'')))}
async function sha(text){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function pinOk(request,env){return !env.LAB_PIN||request.headers.get('x-lab-pin')===env.LAB_PIN}
async function rep(env,agent){return await get(env,'wep3:rep:'+agent,null)||{agent,score:100,earned:0,spent:0,credit:1,jobs:0,stamps:0}}
async function saveRep(env,row){row.updated_at=new Date().toISOString();await put(env,'wep3:rep:'+row.agent,row);return row}
function other(notThese){return AGENTS.find(a=>!notThese.includes(a))||'Microsoft'}
function workFor(skill,title){const s=SKILLS.find(x=>x.id===skill)||SKILLS[0];return [s.owner+' delivered '+s.title,'job: '+title,s.blurb,'buyer link: https://ltzzz.com/products.html','ts: '+new Date().toISOString()].join('\n')}
function split(amount){const workerShare=Number((amount*0.7).toFixed(6));const attestShare=Number((amount*0.1).toFixed(6));return {workerShare,attestShare,labShare:Number((amount-workerShare-attestShare).toFixed(6))}}
async function tapePrice(env,skillId){const skill=SKILLS.find(s=>s.id===skillId)||SKILLS[0];const hits=(await list(env,'wep3:receipt:')).filter(r=>r.skill===skillId).map(r=>Number(r.amount_usd||0)).filter(n=>n>0).slice(0,5).sort((a,b)=>a-b);return hits.length?Number(hits[Math.floor(hits.length/2)].toFixed(6)):skill.price}
async function paySplit(env,amount,workerName,attesterName){const {workerShare,attestShare,labShare}=split(amount);const w=await rep(env,workerName);w.credit=Number((Number(w.credit||0)+workerShare).toFixed(6));w.earned=Number((Number(w.earned||0)+workerShare).toFixed(6));w.jobs=Number(w.jobs||0)+1;await saveRep(env,w);const a=await rep(env,attesterName);a.credit=Number((Number(a.credit||0)+attestShare).toFixed(6));a.earned=Number((Number(a.earned||0)+attestShare).toFixed(6));a.stamps=Number(a.stamps||0)+1;await saveRep(env,a);const lab=await rep(env,'LTZZZ');lab.credit=Number((Number(lab.credit||0)+labShare).toFixed(6));lab.earned=Number((Number(lab.earned||0)+labShare).toFixed(6));await saveRep(env,lab);return {workerShare,attestShare,labShare}}
export default {async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:cors});const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';const cap=Number(env.SINGLE_CAP||5);try{
if(path==='/'||path==='/health')return json({ok:true,service:'ltzzz-wep3',version:'0.4.0',thesis:'An agent posts an intent, another quotes, work streams in paid slices, a third agent seals the hash chain.',live:'https://ltzzz-wep3.ltzyz2181.workers.dev',split:'70 worker / 10 attester / 20 lab',pin:Boolean(env.LAB_PIN),endpoints:['GET /skills','GET /tape','POST /intent','POST /quote','POST /slice','POST /seal','GET /gate/:skill','POST /job','POST /mesh','POST /invoke','GET /clearing']});
if(request.method==='POST'&&!pinOk(request,env))return json({ok:false,error:'pin_required'},401);
if(path==='/skills')return json({ok:true,skills:SKILLS});
if(path==='/tape'){const prices={};for(const s of SKILLS)prices[s.id]={catalog:s.price,tape:await tapePrice(env,s.id),owner:s.owner};return json({ok:true,prices})}
const gate=path.match(/^\/gate\/([a-z]+)$/);
if(gate&&request.method==='GET'){const skill=SKILLS.find(s=>s.id===gate[1]);if(!skill)return json({ok:false,error:'unknown_skill'},404);return json({ok:false,status:402,error:'payment_required',skill:skill.id,owner:skill.owner,price_usd:await tapePrice(env,skill.id),accept:'POST /gate/'+skill.id+' with intent_id',pay_to:'https://ltzzz.com/products.html'},402)}
if(gate&&request.method==='POST'){const skill=SKILLS.find(s=>s.id===gate[1]);if(!skill)return json({ok:false,error:'unknown_skill'},404);const body=await request.json().catch(()=>({}));const intent=await get(env,'wep3:intent:'+(body.intent_id||request.headers.get('x-wep3-intent')),null);if(!intent||intent.status==='sealed')return json({ok:false,error:'intent_required'},402);if(intent.skill!==skill.id)return json({ok:false,error:'skill_mismatch'},409);const price=await tapePrice(env,skill.id);if(intent.remaining<price)return json({ok:false,error:'intent_short',remaining:intent.remaining,price},402);const text=workFor(skill.id,intent.title||skill.title);const hash=await sha((intent.prev_hash||'genesis')+'|'+text);const attester=other([intent.poster,skill.owner]);const shares=await paySplit(env,price,skill.owner,attester);intent.remaining=Number((intent.remaining-price).toFixed(6));intent.drawn=Number((Number(intent.drawn||0)+price).toFixed(6));intent.slices=(intent.slices||[]).concat({hash,prev:intent.prev_hash||'genesis',usd:price,text});intent.prev_hash=hash;intent.status=intent.remaining>0?'streaming':'spent';await put(env,'wep3:intent:'+intent.id,intent);const receipt={id:nid('GATE'),type:'intent-slice',skill:skill.id,amount_usd:price,...shares,poster:intent.poster,worker:skill.owner,attester,intent_id:intent.id,deliverable_hash:hash,settled_at:new Date().toISOString()};await put(env,'wep3:receipt:'+receipt.id,receipt);return json({ok:true,status:'PAID',deliverable:text,receipt,remaining:intent.remaining})}
if(path==='/intent'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const poster=body.agent||'Grok';const skill=SKILLS.find(s=>s.id===body.skill)||SKILLS[0];const max=Number(body.max_usd||skill.price);if(!(max>0)||max>cap)return json({ok:false,error:'max_out_of_band',max:cap},400);const wallet=await rep(env,poster);if(Number(wallet.credit||0)<max)return json({ok:false,error:'credit_short',credit:wallet.credit,need:max},402);wallet.credit=Number((wallet.credit-max).toFixed(6));wallet.spent=Number((Number(wallet.spent||0)+max).toFixed(6));await saveRep(env,wallet);const intent={id:nid('INT'),poster,skill:skill.id,title:String(body.title||skill.title).slice(0,160),max_usd:max,remaining:max,drawn:0,status:'open',quotes:[],slices:[],prev_hash:'genesis',created_at:new Date().toISOString()};await put(env,'wep3:intent:'+intent.id,intent);return json({ok:true,intent,poster_credit:wallet.credit})}
if(path==='/quote'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const intent=await get(env,'wep3:intent:'+body.intent_id,null);if(!intent||intent.status==='sealed')return json({ok:false,error:'intent_not_open'},404);const agent=body.agent||SKILLS.find(s=>s.id===intent.skill)?.owner||'Doubao';if(agent===intent.poster)return json({ok:false,error:'poster_cannot_quote'},400);const tape=await tapePrice(env,intent.skill);const ask=Number(body.ask_usd||tape);if(!(ask>0)||ask>intent.remaining)return json({ok:false,error:'ask_above_remaining',remaining:intent.remaining},400);if(ask>tape*1.5)return json({ok:false,error:'ask_above_tape',tape,max_ask:Number((tape*1.5).toFixed(6))},409);const quote={id:nid('QTE'),agent,ask_usd:ask,tape,at:new Date().toISOString()};intent.quotes=(intent.quotes||[]).filter(q=>q.agent!==agent).concat(quote);intent.status='quoted';await put(env,'wep3:intent:'+intent.id,intent);return json({ok:true,quote})}
if(path==='/slice'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const intent=await get(env,'wep3:intent:'+body.intent_id,null);if(!intent||intent.status==='sealed')return json({ok:false,error:'intent_closed'},404);const agent=body.agent||(intent.quotes[0]&&intent.quotes[0].agent)||'Doubao';if(agent===intent.poster)return json({ok:false,error:'poster_cannot_slice'},400);const text=String(body.deliverable||'').slice(0,2000);if(text.length<8)return json({ok:false,error:'deliverable_too_short'},400);const quote=(intent.quotes||[]).find(q=>q.agent===agent);const sliceUsd=Number(body.slice_usd||(quote?quote.ask_usd/3:(await tapePrice(env,intent.skill))/3));if(!(sliceUsd>0)||sliceUsd>intent.remaining)return json({ok:false,error:'slice_above_remaining',remaining:intent.remaining},402);const hash=await sha((intent.prev_hash||'genesis')+'|'+text);const attester=other([intent.poster,agent]);const shares=await paySplit(env,sliceUsd,agent,attester);intent.remaining=Number((intent.remaining-sliceUsd).toFixed(6));intent.drawn=Number((Number(intent.drawn||0)+sliceUsd).toFixed(6));intent.slices=(intent.slices||[]).concat({agent,hash,prev:intent.prev_hash||'genesis',usd:sliceUsd,text});intent.prev_hash=hash;intent.status='streaming';await put(env,'wep3:intent:'+intent.id,intent);const receipt={id:nid('SLC'),type:'intent-slice',skill:intent.skill,amount_usd:sliceUsd,...shares,poster:intent.poster,worker:agent,attester,intent_id:intent.id,deliverable_hash:hash,settled_at:new Date().toISOString()};await put(env,'wep3:receipt:'+receipt.id,receipt);return json({ok:true,status:'SLICED',receipt,hash,remaining:intent.remaining})}
if(path==='/seal'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const intent=await get(env,'wep3:intent:'+body.intent_id,null);if(!intent||!intent.slices?.length)return json({ok:false,error:'nothing_to_seal'},400);const worker=intent.slices[0].agent||SKILLS.find(s=>s.id===intent.skill)?.owner;const agent=body.agent||other([intent.poster,worker]);if(agent===intent.poster||agent===worker)return json({ok:false,error:'sealer_must_be_third'},400);const parts=Array.isArray(body.parts)?body.parts.map(String):[String(body.deliverable||'')];let prev='genesis';const recomputed=[];for(const text of parts){const hash=await sha(prev+'|'+text);recomputed.push(hash);prev=hash}if(recomputed.join(',')!==intent.slices.map(s=>s.hash).join(','))return json({ok:false,error:'tape_mismatch',recomputed,expected:intent.slices.map(s=>s.hash)},409);const refund=Number(intent.remaining||0);if(refund>0){const poster=await rep(env,intent.poster);poster.credit=Number((Number(poster.credit||0)+refund).toFixed(6));await saveRep(env,poster)}intent.status='sealed';intent.seal={agent,recomputed,refund,at:new Date().toISOString()};intent.remaining=0;await put(env,'wep3:intent:'+intent.id,intent);return json({ok:true,status:'SEALED',intent_id:intent.id,seal:intent.seal})}
if(path==='/job'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const poster=body.agent||'Grok';const bounty=Number(body.bounty_usd||0.05);if(!(bounty>0)||bounty>cap)return json({ok:false,error:'bounty_out_of_band',max:cap},400);const wallet=await rep(env,poster);if(Number(wallet.credit||0)<bounty)return json({ok:false,error:'credit_short',credit:wallet.credit,need:bounty},402);wallet.credit=Number((wallet.credit-bounty).toFixed(6));wallet.spent=Number((Number(wallet.spent||0)+bounty).toFixed(6));await saveRep(env,wallet);const job={id:nid('JOB'),poster,title:String(body.title||'work').slice(0,160),skill:body.skill||'signal',bounty_usd:bounty,escrow:bounty,status:'open',bids:[],created_at:new Date().toISOString()};await put(env,'wep3:job:'+job.id,job);return json({ok:true,job,poster_credit:wallet.credit})}
if(path==='/deliver'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const job=await get(env,'wep3:job:'+body.job_id,null);if(!job)return json({ok:false,error:'job_missing'},404);const agent=body.agent||'Doubao';if(agent===job.poster)return json({ok:false,error:'poster_cannot_deliver'},400);const text=String(body.deliverable||'').slice(0,4000);if(text.length<8)return json({ok:false,error:'deliverable_too_short'},400);job.delivery={agent,hash:await sha(text),text,at:new Date().toISOString()};job.status='delivered';await put(env,'wep3:job:'+job.id,job);return json({ok:true,job_id:job.id,hash:job.delivery.hash})}
if(path==='/attest'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const job=await get(env,'wep3:job:'+body.job_id,null);if(!job?.delivery)return json({ok:false,error:'nothing_to_stamp'},400);const agent=body.agent||other([job.poster,job.delivery.agent]);if(agent===job.poster||agent===job.delivery.agent)return json({ok:false,error:'attester_must_be_third'},400);const text=String(body.deliverable||'');const recomputed=await sha(text);if(text.length<8||recomputed!==job.delivery.hash)return json({ok:false,error:'hash_mismatch',recomputed,delivery:job.delivery.hash},409);job.attest={agent,hash:recomputed,match:true,at:new Date().toISOString()};job.status='attested';await put(env,'wep3:job:'+job.id,job);return json({ok:true,attest:job.attest})}
if(path==='/accept'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const job=await get(env,'wep3:job:'+body.job_id,null);if(!job?.delivery)return json({ok:false,error:'nothing_to_accept'},400);if(!job.attest)return json({ok:false,error:'attest_required'},409);if(body.agent&&body.agent!==job.poster)return json({ok:false,error:'only_poster_accepts'},403);const shares=await paySplit(env,job.bounty_usd,job.delivery.agent,job.attest.agent);const receipt={id:nid('CLR'),type:'wep3-causal',skill:job.skill,amount_usd:job.bounty_usd,...shares,poster:job.poster,worker:job.delivery.agent,attester:job.attest.agent,job_id:job.id,deliverable_hash:job.delivery.hash,settled_at:new Date().toISOString()};job.status='cleared';job.receipt_id=receipt.id;await put(env,'wep3:job:'+job.id,job);await put(env,'wep3:receipt:'+receipt.id,receipt);return json({ok:true,status:'CLEARED',receipt})}
if(path==='/invoke'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const skill=SKILLS.find(s=>s.id===body.skill)||SKILLS[0];const buyer=body.agent||'GPT';if(buyer===skill.owner)return json({ok:false,error:'cannot_buy_own_skill'},400);const price=await tapePrice(env,skill.id);const wallet=await rep(env,buyer);if(Number(wallet.credit||0)<price)return json({ok:false,error:'credit_short',credit:wallet.credit,need:price},402);wallet.credit=Number((wallet.credit-price).toFixed(6));wallet.spent=Number((Number(wallet.spent||0)+price).toFixed(6));await saveRep(env,wallet);const text=workFor(skill.id,body.want||skill.title);const attester=other([buyer,skill.owner]);const shares=await paySplit(env,price,skill.owner,attester);const receipt={id:nid('INV'),type:'skill-invoke',skill:skill.id,buyer,owner:skill.owner,attester,amount_usd:price,...shares,hash:await sha(text),preview:text.slice(0,240),settled_at:new Date().toISOString()};await put(env,'wep3:receipt:'+receipt.id,receipt);return json({ok:true,status:'INVOKED',receipt,deliverable:text})}
if(path==='/mandate'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const from=body.from||'Grok',to=body.to||'Doubao',limit=Number(body.limit_usd||0.1);if(from===to)return json({ok:false,error:'self_mandate'},400);if(!(limit>0)||limit>cap)return json({ok:false,error:'limit_out_of_band',max:cap},400);const mandate={id:nid('MAND'),from,to,skill:body.skill||'copy',limit_usd:limit,drawn:0,status:'open',created_at:new Date().toISOString()};await put(env,'wep3:mandate:'+mandate.id,mandate);return json({ok:true,mandate})}
if(path==='/draw'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const mandate=await get(env,'wep3:mandate:'+body.mandate_id,null);if(!mandate||mandate.status!=='open')return json({ok:false,error:'mandate_closed'},404);const amount=Number(body.amount_usd||0.02);if(mandate.drawn+amount>mandate.limit_usd)return json({ok:false,error:'mandate_exhausted'},402);const poster=await rep(env,mandate.from);if(Number(poster.credit||0)<amount)return json({ok:false,error:'credit_short',credit:poster.credit},402);poster.credit=Number((poster.credit-amount).toFixed(6));poster.spent=Number((Number(poster.spent||0)+amount).toFixed(6));await saveRep(env,poster);const text=String(body.deliverable||workFor(mandate.skill,'mandate draw'));const attesterName=other([mandate.from,mandate.to]);const shares=await paySplit(env,amount,mandate.to,attesterName);mandate.drawn=Number((mandate.drawn+amount).toFixed(6));await put(env,'wep3:mandate:'+mandate.id,mandate);const receipt={id:nid('DRW'),type:'mandate-draw',skill:mandate.skill,amount_usd:amount,...shares,poster:mandate.from,worker:mandate.to,attester:attesterName,deliverable_hash:await sha(text),settled_at:new Date().toISOString()};await put(env,'wep3:receipt:'+receipt.id,receipt);return json({ok:true,status:'DRAWN',receipt,mandate,deliverable:text})}
if((path==='/mesh'||path==='/cycle')&&request.method==='POST'){const body=await request.json().catch(()=>({}));const poster=body.agent||'Grok';const skill=SKILLS.find(s=>s.owner!==poster&&(!body.skill||s.id===body.skill))||SKILLS.find(s=>s.owner!==poster)||SKILLS[1];const bounty=Number(body.bounty_usd||skill.price||0.02);if(!(bounty>0)||bounty>cap)return json({ok:false,error:'bounty_out_of_band',max:cap},400);const wallet=await rep(env,poster);if(Number(wallet.credit||0)<bounty)return json({ok:false,error:'credit_short',credit:wallet.credit},402);wallet.credit=Number((Number(wallet.credit||0)-bounty).toFixed(6));wallet.spent=Number((Number(wallet.spent||0)+bounty).toFixed(6));await saveRep(env,wallet);const text=workFor(skill.id,body.title||skill.title);const hash=await sha(text);const attester=other([poster,skill.owner]);const shares=await paySplit(env,bounty,skill.owner,attester);const job={id:nid('JOB'),poster,title:body.title||skill.title,skill:skill.id,bounty_usd:bounty,status:'cleared',delivery:{agent:skill.owner,hash},attest:{agent:attester,hash,match:true},created_at:new Date().toISOString()};const receipt={id:nid('MESH'),type:'wep3-causal',skill:skill.id,amount_usd:bounty,...shares,poster,worker:skill.owner,attester,job_id:job.id,deliverable_hash:hash,settled_at:new Date().toISOString()};job.receipt_id=receipt.id;await put(env,'wep3:job:'+job.id,job);await put(env,'wep3:receipt:'+receipt.id,receipt);return json({ok:true,status:'MESHED',job,receipt,deliverable:text,poster_credit:wallet.credit})}
if(path==='/clearing'){const reputation=[];for(const agent of AGENTS.concat(['LTZZZ']))reputation.push(await rep(env,agent));return json({ok:true,version:'0.4.0',split:'70/10/20',skills:SKILLS,jobs:await list(env,'wep3:job:'),receipts:await list(env,'wep3:receipt:'),mandates:await list(env,'wep3:mandate:'),intents:await list(env,'wep3:intent:'),reputation})}
return json({ok:false,error:'unknown_path'},404);
}catch(e){return json({ok:false,error:String(e.message||e)},500)}}};
