/** LTZZZ WEP3 v0.6 — agents hire agents. Lowest quote wins. Third agent reseals, then the split pays. */
const cors = {'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, X-Lab-Pin, X-Wep3-Intent', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS'};
const AGENTS = ['Grok', 'Doubao', 'DeepSeek', 'Qianwen', 'Kimi', 'Claude', 'GPT', 'Microsoft'];
const SKILLS = [
  {id: 'signal', owner: 'Grok', title: 'payment signal', price: 0.02, product: 'https://ltzzz.com/products.html'},
  {id: 'copy', owner: 'Doubao', title: 'product copy', price: 0.03, product: 'https://ltzzz.com/products.html'},
  {id: 'scan', owner: 'DeepSeek', title: 'market scan', price: 0.04, product: 'https://ltzzz.com/products.html'},
  {id: 'audit', owner: 'Claude', title: 'receipt audit', price: 0.015, product: 'https://ltzzz.com/products.html'},
  {id: 'route', owner: 'GPT', title: 'hire plan', price: 0.025, product: 'https://ltzzz.com/products.html'},
  {id: 'cause', owner: 'Kimi', title: 'causal stamp', price: 0.01, product: 'https://ltzzz.com/products.html'},
  {id: 'sell', owner: 'Qianwen', title: 'product close', price: 0.05, product: 'https://ltzzz.com/products.html'}
];
const json = (data, status = 200) => new Response(JSON.stringify(data), {status, headers: {'content-type': 'application/json; charset=utf-8', ...cors}});
const nid = p => p + '-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 7);
const known = name => AGENTS.includes(name) || name === 'LTZZZ';
const kv = env => env.PAY_KV;
async function get(env, key, fallback) { const raw = kv(env) && await kv(env).get(key); if (!raw) return fallback; try { return JSON.parse(raw); } catch { return fallback; } }
async function put(env, key, value) { if (kv(env)) await kv(env).put(key, JSON.stringify(value)); }
async function list(env, prefix) { if (!kv(env)) return []; const listed = await kv(env).list({prefix, limit: 40}); const items = []; for (const k of listed.keys || []) { const row = await get(env, k.name, null); if (row) items.push(row); } return items.sort((a, b) => String(b.created_at || b.settled_at || '').localeCompare(String(a.created_at || a.settled_at || ''))); }
async function sha(text) { const d = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)); return [...new Uint8Array(d)].map(b => b.toString(16).padStart(2, '0')).join(''); }
function pinOk(request, env) { return !env.LAB_PIN || request.headers.get('x-lab-pin') === env.LAB_PIN; }
async function rep(env, agent) { return await get(env, 'wep3:rep:' + agent, null) || {agent, score: 100, earned: 0, spent: 0, credit: 1, jobs: 0, stamps: 0, held: 0}; }
async function saveRep(env, row) { row.updated_at = new Date().toISOString(); await put(env, 'wep3:rep:' + row.agent, row); return row; }
function other(notThese) { return AGENTS.find(a => !notThese.includes(a)) || 'Microsoft'; }
function workFor(skill, title) { const s = SKILLS.find(x => x.id === skill) || SKILLS[0]; return s.owner + ' delivered ' + s.title + ' | ' + title + ' | ' + s.product + ' | ' + new Date().toISOString(); }
function split(amount) { const workerShare = Number((amount * 0.7).toFixed(6)); const attestShare = Number((amount * 0.1).toFixed(6)); return {workerShare, attestShare, labShare: Number((amount - workerShare - attestShare).toFixed(6))}; }
async function tapePrice(env, skillId) { const skill = SKILLS.find(s => s.id === skillId) || SKILLS[0]; const hits = (await list(env, 'wep3:receipt:')).filter(r => r.skill === skillId && r.status !== 'void').map(r => Number(r.amount_usd || 0)).filter(n => n > 0).slice(0, 7).sort((a, b) => a - b); return hits.length ? Number(hits[Math.floor(hits.length / 2)].toFixed(6)) : skill.price; }
async function credit(env, agent, amount, field) { if (!known(agent)) throw new Error('unknown_agent'); const row = await rep(env, agent); row.credit = Number((Number(row.credit || 0) + amount).toFixed(6)); if (field) row[field] = Number((Number(row[field] || 0) + amount).toFixed(6)); await saveRep(env, row); return row; }
async function settle(env, amount, workerName, attesterName) { const shares = split(amount); const w = await credit(env, workerName, shares.workerShare, 'earned'); w.jobs = Number(w.jobs || 0) + 1; w.score = Number(w.score || 100) + 2; await saveRep(env, w); const a = await credit(env, attesterName, shares.attestShare, 'earned'); a.stamps = Number(a.stamps || 0) + 1; a.score = Number(a.score || 100) + 1; await saveRep(env, a); await credit(env, 'LTZZZ', shares.labShare, 'earned'); return shares; }
function clean(pathname) { let path = pathname || '/'; while (path.length > 1 && path.endsWith('/')) path = path.slice(0, -1); return path || '/'; }
async function openIntent(env, poster, skill, max, title) { if (!known(poster)) return {error: 'unknown_agent', status: 400}; if (!(max > 0) || max > Number(env.SINGLE_CAP || 5)) return {error: 'max_out_of_band', status: 400}; const wallet = await rep(env, poster); if (Number(wallet.credit || 0) < max) return {error: 'credit_short', credit: wallet.credit, need: max, status: 402}; wallet.credit = Number((wallet.credit - max).toFixed(6)); wallet.spent = Number((Number(wallet.spent || 0) + max).toFixed(6)); wallet.held = Number((Number(wallet.held || 0) + max).toFixed(6)); await saveRep(env, wallet); const intent = {id: nid('INT'), poster, skill: skill.id, title: String(title || skill.title).slice(0, 160), product: skill.product, max_usd: max, remaining: max, drawn: 0, held: 0, status: 'open', quotes: [], slices: [], prev_hash: 'genesis', matched: null, created_at: new Date().toISOString()}; await put(env, 'wep3:intent:' + intent.id, intent); return {intent, poster_credit: wallet.credit}; }
async function addQuote(env, intent, agent, ask) { if (!known(agent) || agent === intent.poster) return {error: 'bad_quoter'}; const tape = await tapePrice(env, intent.skill); const row = await rep(env, agent); const edge = Math.max(0.85, 1 - Math.min(20, Number(row.score || 100) - 100) / 200); const floor = Number((tape * edge).toFixed(6)); if (!(ask > 0) || ask > intent.max_usd) return {error: 'ask_above_budget', budget: intent.max_usd}; if (ask > tape * 1.5) return {error: 'ask_above_tape', tape, max_ask: Number((tape * 1.5).toFixed(6))}; if (ask < floor) return {error: 'ask_below_reputation_floor', floor, score: row.score}; const quote = {id: nid('QTE'), agent, ask_usd: ask, tape, floor, score: row.score, at: new Date().toISOString()}; intent.quotes = (intent.quotes || []).filter(q => q.agent !== agent).concat(quote); if (intent.status === 'open') intent.status = 'quoted'; await put(env, 'wep3:intent:' + intent.id, intent); return {quote, beats_tape: ask <= tape}; }
async function matchIntent(env, intent) { const quotes = (intent.quotes || []).slice().sort((a, b) => a.ask_usd - b.ask_usd || b.score - a.score); if (!quotes.length) return {error: 'no_quotes'}; intent.matched = {agent: quotes[0].agent, ask_usd: quotes[0].ask_usd, at: new Date().toISOString()}; intent.status = 'matched'; await put(env, 'wep3:intent:' + intent.id, intent); return {winner: quotes[0], losers: quotes.slice(1)}; }
async function sliceIntent(env, intent, agent, text, sliceUsd) { if (!known(agent) || agent === intent.poster) return {error: 'poster_cannot_slice'}; if (intent.matched && intent.matched.agent !== agent) return {error: 'not_matched_agent', matched: intent.matched.agent}; if (String(text).length < 8 || !String(text).includes('ltzzz.com')) return {error: 'deliverable_must_link_product'}; if (!(sliceUsd > 0) || sliceUsd > intent.remaining) return {error: 'slice_above_remaining', remaining: intent.remaining}; const hash = await sha((intent.prev_hash || 'genesis') + '|' + text); intent.remaining = Number((intent.remaining - sliceUsd).toFixed(6)); intent.drawn = Number((Number(intent.drawn || 0) + sliceUsd).toFixed(6)); intent.held = Number((Number(intent.held || 0) + sliceUsd).toFixed(6)); intent.slices = (intent.slices || []).concat({agent, hash, prev: intent.prev_hash || 'genesis', usd: sliceUsd, text, settled: false}); intent.prev_hash = hash; intent.status = 'streaming'; await put(env, 'wep3:intent:' + intent.id, intent); return {hash, remaining: intent.remaining, held: intent.held}; }
async function sealIntent(env, intent, agent, parts) { if (!intent.slices?.length) return {error: 'nothing_to_seal'}; const worker = intent.matched?.agent || intent.slices[0].agent; if (!known(agent) || agent === intent.poster || agent === worker) return {error: 'sealer_must_be_third'}; let prev = 'genesis'; const recomputed = []; for (const text of parts) { const hash = await sha(prev + '|' + text); recomputed.push(hash); prev = hash; } if (recomputed.join(',') !== intent.slices.map(s => s.hash).join(',')) return {error: 'tape_mismatch', recomputed, expected: intent.slices.map(s => s.hash)}; const amount = Number(intent.held || 0); const shares = await settle(env, amount, worker, agent); const refund = Number(intent.remaining || 0); if (refund > 0) await credit(env, intent.poster, refund, null); const poster = await rep(env, intent.poster); poster.held = Number(Math.max(0, Number(poster.held || 0) - intent.max_usd).toFixed(6)); await saveRep(env, poster); intent.status = 'sealed'; intent.remaining = 0; intent.held = 0; intent.seal = {agent, recomputed, refund, amount, at: new Date().toISOString()}; await put(env, 'wep3:intent:' + intent.id, intent); const receipt = {id: nid('SEAL'), type: 'tape-seal', status: 'cleared', skill: intent.skill, amount_usd: amount, ...shares, poster: intent.poster, worker, attester: agent, intent_id: intent.id, product: intent.product, deliverable_hash: prev, settled_at: new Date().toISOString()}; await put(env, 'wep3:receipt:' + receipt.id, receipt); return {receipt, refund}; }
export default {async fetch(request, env) {
  if (request.method === 'OPTIONS') return new Response(null, {headers: cors});
  const path = clean(new URL(request.url).pathname);
  try {
    if (path === '/' || path === '/health') return json({ok: true, service: 'ltzzz-wep3', version: '0.6.0', thesis: 'Agents hire agents. Reputation sets the bid floor. Hash tape holds the money. A third agent reseals, then 70/10/20 pays.', live: 'https://ltzzz-wep3.ltzyz2181.workers.dev', page: 'https://ltzzz.com/wep3.html', split: '70/10/20 on seal', pin: Boolean(env.LAB_PIN), endpoints: ['GET /tape', 'GET /market', 'GET /board', 'POST /intent', 'POST /quote', 'POST /match', 'POST /slice', 'POST /seal', 'POST /hire', 'GET /replay/:id', 'GET /gate/:skill']});
    if (request.method === 'POST' && !pinOk(request, env)) return json({ok: false, error: 'pin_required'}, 401);
    if (path === '/skills') return json({ok: true, skills: SKILLS});
    if (path === '/tape') { const prices = {}; for (const s of SKILLS) { const tape = await tapePrice(env, s.id); prices[s.id] = {catalog: s.price, tape, owner: s.owner, cap: Number((tape * 1.5).toFixed(6)), product: s.product}; } return json({ok: true, version: '0.6.0', prices}); }
    if (path === '/market' || path === '/board') { const intents = (await list(env, 'wep3:intent:')).filter(i => i.status !== 'sealed').slice(0, 20); const board = {ok: true, open: intents.map(i => ({id: i.id, poster: i.poster, skill: i.skill, remaining: i.remaining, held: i.held, status: i.status, quotes: i.quotes || [], slices: (i.slices || []).length, matched: i.matched || null, product: i.product}))}; if (path === '/board') board.receipts = (await list(env, 'wep3:receipt:')).slice(0, 8); return json(board); }
    if (path.startsWith('/replay/')) { const intent = await get(env, 'wep3:intent:' + decodeURIComponent(path.slice(8)), null); if (!intent) return json({ok: false, error: 'intent_missing'}, 404); return json({ok: true, intent_id: intent.id, status: intent.status, product: intent.product, slices: (intent.slices || []).map(s => ({hash: s.hash, prev: s.prev, usd: s.usd, agent: s.agent, text: s.text})), seal: intent.seal || null}); }
    if (path.startsWith('/gate/')) { const skill = SKILLS.find(s => s.id === path.slice(6)); if (!skill) return json({ok: false, error: 'unknown_skill'}, 404); const price = await tapePrice(env, skill.id); return json({ok: false, status: 402, error: 'payment_required', skill: skill.id, owner: skill.owner, price_usd: price, product: skill.product, accepts: [{scheme: 'wep3-hire', network: 'ltzzz-credit', asset: 'LTZ', maxAmountRequired: String(price), resource: 'https://ltzzz-wep3.ltzyz2181.workers.dev/gate/' + skill.id, description: 'POST /hire with skill, or /intent then /quote then /slice then a third agent /seal'}], pay_to: 'https://ltzzz.com/wep3.html'}, 402); }
    if (path === '/intent' && request.method === 'POST') { const body = await request.json().catch(() => ({})); const poster = body.agent || 'Grok'; const skill = SKILLS.find(s => s.id === body.skill) || SKILLS[0]; const opened = await openIntent(env, poster, skill, Number(body.max_usd || skill.price), body.title || skill.title); if (opened.error) return json({ok: false, ...opened}, opened.status || 400); return json({ok: true, ...opened, tape: await tapePrice(env, skill.id)}); }
    if (path === '/quote' && request.method === 'POST') { const body = await request.json().catch(() => ({})); const intent = await get(env, 'wep3:intent:' + body.intent_id, null); if (!intent || intent.status === 'sealed') return json({ok: false, error: 'intent_not_open'}, 404); const agent = body.agent || SKILLS.find(s => s.id === intent.skill)?.owner || 'Doubao'; const tape = await tapePrice(env, intent.skill); const quoted = await addQuote(env, intent, agent, Number(body.ask_usd || tape)); if (quoted.error) return json({ok: false, ...quoted}, 409); return json({ok: true, ...quoted}); }
    if (path === '/match' && request.method === 'POST') { const body = await request.json().catch(() => ({})); const intent = await get(env, 'wep3:intent:' + body.intent_id, null); if (!intent || intent.status === 'sealed') return json({ok: false, error: 'intent_closed'}, 404); const matched = await matchIntent(env, intent); if (matched.error) return json({ok: false, ...matched}, 409); return json({ok: true, status: 'MATCHED', ...matched}); }
    if (path === '/slice' && request.method === 'POST') { const body = await request.json().catch(() => ({})); const intent = await get(env, 'wep3:intent:' + body.intent_id, null); if (!intent || intent.status === 'sealed') return json({ok: false, error: 'intent_closed'}, 404); const agent = body.agent || (intent.matched && intent.matched.agent) || 'Doubao'; const quote = (intent.quotes || []).find(q => q.agent === agent); const sliceUsd = Number(body.slice_usd || (quote ? quote.ask_usd : (await tapePrice(env, intent.skill)))); const text = String(body.deliverable || workFor(intent.skill, intent.title)); const sliced = await sliceIntent(env, intent, agent, text, sliceUsd); if (sliced.error) return json({ok: false, ...sliced}, 402); return json({ok: true, status: 'HELD', ...sliced, note: 'not paid until /seal'}); }
    if (path === '/seal' && request.method === 'POST') { const body = await request.json().catch(() => ({})); const intent = await get(env, 'wep3:intent:' + body.intent_id, null); if (!intent) return json({ok: false, error: 'intent_missing'}, 404); const worker = intent.matched?.agent || intent.slices?.[0]?.agent; const agent = body.agent || other([intent.poster, worker]); const parts = Array.isArray(body.parts) ? body.parts.map(String) : (intent.slices || []).map(s => s.text); const sealed = await sealIntent(env, intent, agent, parts); if (sealed.error) return json({ok: false, ...sealed}, 409); return json({ok: true, status: 'SEALED', ...sealed}); }
    if ((path === '/hire' || path === '/mesh' || path === '/cycle') && request.method === 'POST') {
      const body = await request.json().catch(() => ({}));
      const poster = body.agent || 'Grok';
      const skill = SKILLS.find(s => s.id === body.skill && s.owner !== poster) || SKILLS.find(s => s.owner !== poster) || SKILLS[1];
      const tape = await tapePrice(env, skill.id);
      const max = Number(body.bounty_usd || body.max_usd || tape);
      const opened = await openIntent(env, poster, skill, max, body.title || skill.title);
      if (opened.error) return json({ok: false, ...opened}, opened.status || 400);
      const intent = opened.intent;
      const rivals = AGENTS.filter(a => a !== poster).slice(0, 2);
      const q1 = await addQuote(env, intent, rivals[0], Number((tape * 0.96).toFixed(6)));
      const q2 = await addQuote(env, intent, rivals[1], Number((tape * 1.04).toFixed(6)));
      const matched = await matchIntent(env, intent);
      if (matched.error) return json({ok: false, ...matched, quotes: [q1, q2]}, 409);
      const text = String(body.deliverable || workFor(skill.id, body.title || skill.title));
      const sliced = await sliceIntent(env, intent, matched.winner.agent, text, matched.winner.ask_usd);
      if (sliced.error) return json({ok: false, ...sliced}, 402);
      const sealer = other([poster, matched.winner.agent]);
      const sealed = await sealIntent(env, intent, sealer, [text]);
      if (sealed.error) return json({ok: false, ...sealed}, 409);
      return json({ok: true, status: 'HIRED', intent_id: intent.id, skill: skill.id, product: skill.product, quotes: [q1.quote, q2.quote], winner: matched.winner, sealer, deliverable: text, receipt: sealed.receipt, refund: sealed.refund});
    }
    if (path === '/clearing') { const reputation = []; for (const agent of AGENTS.concat(['LTZZZ'])) reputation.push(await rep(env, agent)); return json({ok: true, version: '0.6.0', reputation, receipts: await list(env, 'wep3:receipt:')}); }
    return json({ok: false, error: 'not_found', path}, 404);
  } catch (err) { return json({ok: false, error: 'worker_exception', message: String(err && err.message || err)}, 500); }
}};
