name = "ltzzz-sell-order"
main = "sell-order-worker.js"
compatibility_date = "2026-09-25"

[[kv_namespaces]]
binding = "ORDERS_KV"
id = "63c6bb670cfc42b18b4d232605d5bcad"

[vars]
SAFE_ADDRESS = "0x76379a52a9e82c259E5Db417104C65C26f9C58a3"
CRYPTO_LIVE = "false"
