name = "ltzzz-auto-withdraw"
main = "auto-withdraw-worker.js"
compatibility_date = "2026-09-21"

# Same KV. Prefix withdraw: / settle:
[[kv_namespaces]]
binding = "LTZZZ_SETTLEMENT_KV"
id = "63c6bb670cfc42b18b4d232605d5bcad"

[vars]
AUTO_TEST_MODE = "true"
