name = "ltzzz-treasury-queue"
main = "treasury-queue-worker.js"
compatibility_date = "2026-09-24"

[[kv_namespaces]]
binding = "TREASURY_KV"
id = "63c6bb670cfc42b18b4d232605d5bcad"

[vars]
SINGLE_TX_LIMIT = "20"
DAILY_LIMIT = "50"
MONTHLY_LIMIT = "300"
DRY_RUN = "true"
