name = "ltzzz-r2-public"
main = "r2-public-worker.js"
compatibility_date = "2026-10-01"

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "ltzzz-videos"

[[routes]]
pattern = "videos.ltzzz.com/*"
zone_name = "ltzzz.com"
