name = "ltzzz-agi-pay"
main = "agi-pay-worker.js"
compatibility_date = "2026-09-30"

[[kv_namespaces]]
binding = "PAY_KV"
id = "63c6bb670cfc42b18b4d232605d5bcad"

[vars]
DRY_RUN = "true"
AGI_PAY_DAILY = "50"
AGI_PAY_SINGLE = "5"
AGI_PAY_TICK = "0.0002"
BREAKER_OPEN = "false"
