name = "ltzzz-youtube-daily"
main = "ltzzz-youtube-daily-worker.js"
compatibility_date = "2026-09-11"

[[kv_namespaces]]
binding = "KV"
id = "63c6bb670cfc42b18b4d232605d5bcad"

[triggers]
crons = ["0 9 * * *"]  # 每天早上9点自动运行
